# Generated by Django 5.2.8 on 2025-11-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('prioridad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('etiquetas', models.CharField(choices=[('escuela', 'Escuela'), ('familia', 'Familia'), ('ocio', 'Ocio'), ('social', 'Social'), ('salud', 'Salud'), ('hogar', 'Hogar')], max_length=20)),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
    ]
